Features/module4 home work
Anatoliyfet/java-homework pull request #5
Opened 2023-11-11 08:48 UTC by Anatoliyfet

Hello.
Homework for module 04.
Please, give me some rrecommendations for correctly alignment of the model @mockito for test classes.
Best regards,
Anatoliy.

2023-11-12 12:10 UTC, rsmitt commented on module04/src/main/java/ru/sberbank/edu/Person.java
> +        return Objects.hash(name, city, age);
У вас hashCode не учитывает регистр, equals учитывает. Получается что по equals объекты равно, но по hashCode не равны могут быть. Это не правильно. Если по equals равны то по hashCode должны быть равны, если по hashCode равны, это не означает что по equals будут равны. Надо запомнить это правило. В вашем случае будут происходить коллизии.

2023-11-12 12:12 UTC, rsmitt commented on module04/src/test/java/ru/sberbank/edu/CustomDigitComparatorTest.java
> +    @Mock
Мок нужен когда мы хотим не реальный объект использовать а его заглушку. Т.е. говорим что когда у заглушки держится такой то метод, верни заглушенные данные. В вашем случае этого не происходит и пользы от Мок объекта нет

2023-11-12 12:13 UTC, rsmitt requested changes
прошу поправить hashCode

2023-11-12 13:08 UTC, Anatoliyfet commented
Add fix hashCode.

2023-11-18 16:02 UTC, rsmitt approved these changes

2023-11-27 14:31 UTC, merged